config/routes.rb
Rails.application.routes.draw do

  root to: 'questions#index'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  resources :questions, except: [:new] do
    resources :answers, only: [:create]
  end

  match '/register', to: 'users#new', via: :get
  match '/login', to: 'sessions#new', via: :get
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/your_questions', to: 'questions#your_questions', via: :get
  match '/search', to:  'questions#search', via: [:get, :post]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :body, presence: true, length: {in: 2..255}

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :body, presence: true, length: {in: 10..255}
  validates :solved, inclusion: {in: [true, false]}

  def self.unsolved(params)
  	where(:solved => false).paginate(:page => params[:page], :per_page => 3).order('created_at DESC')
  end

  def self.search(params)
  	where("body LIKE ?", "%#{params[:keyword]}%").paginate(:page => params[:page], :per_page => 3).order('created_at DESC') 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :answers
	has_secure_password

	validates :username, presence: true, uniqueness: {case_sensitive: false},
						length: {in: 4..12},
						format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }

	validates :password, length: {in: 4..14}	
	validates :password_confirmation, length: {in: 4..14}	

	def your_questions(params)
		questions.paginate(:page => params[:page], :per_page => 3).order('created_at DESC')				
	end				
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
before_filter :auth, only: [:create]

	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.build(answer_params)
		@answer.user = current_user

		if @answer.save
			flash[:success] = 'Your answer has been posted!'
			redirect_to @question
		else
			@question = Question.find(params[:question_id])
			render 'questions/show'
		end	
	end

private

  def answer_params
  	params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method [:current_user, :logged_in?]

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
  	current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!current_user.nil?
  end

  def auth
    redirect_to login_url, alert: 'You must login to access that page' unless logged_in?
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :auth, only: [:create, :your_questions, :edit, :update]

  def index
  	@question = Question.new
    @questions = Question.unsolved(params)
  end

  def create
  	@question = current_user.questions.build(question_params)
  	if @question.save
  		flash[:success] = 'Your question has been posted!'
  		redirect_to @question
  	else
      @questions = Question.unsolved(params)
  		render 'index'
  	end
  end

  def show
    @question = Question.find(params[:id])
    @answer= Answer.new
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end
  
  def your_questions
    @questions = current_user.your_questions(params)
  end

  def update
    @question = current_user.questions.find(params[:id])
    if @question.update_attributes(question_params)
      flash[:success] = 'Your question has been updated'
      redirect_to @question
    else
      render 'edit'
    end    
  end

  def search
    @questions= Question.search(params)
  end

  private

  def question_params
  	params.require(:question).permit(:body, :solved)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:username])
  	if user && user.authenticate(params[:password])
  		login user
  		flash[:sucess] = 'You are now logged in!'
  		redirect_to root_url
  	else
  		flash.now[:error] = 'Your username/password combination was incorrect.'
  		render 'new'
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You are now logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new (user_params)
  	if @user.save
  		flash[:success] = 'Thanks for registering'
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end


  private

  def user_params
  	params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
	def on_your_questions_page?
		action_name == 'your_questions'
	end

	def display_solved(question)
		(question.solved) ? ' - (Solved)' : ''
		
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<li>
	<%= answer.body %> - by <%= answer.user.username.capitalize %>
</li>

app/views/answers/_answer_form.html.erb
<%= form_for [@question, @answer] do |f| -%>
  <%= render 'common/form_errors', object: @answer %>

  <p>
  	<%= f.label :body, "Answer" %>
  	<%= f.text_field :body %>
  	<%= f.submit "Post Answer" %>
  </p>
<% end %>

app/views/common/_form_errors.html.erb
<% if object.errors.any? %>
	<ul id="form-errors">
		<% object.errors.full_messages.each do |message| %>
		<li><%= message %></li>	
		<% end %>
	</ul>	
<% end %>

app/views/common/_search_form.html.erb
<%= form_tag(search_path) do %>
  <%= text_field_tag :keyword %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<div id="header">
		<%= link_to 'StackOverflow Clone', root_path %>
		<div id="searchbar">
			<%= render 'common/search_form' %>
		</div>
	</div><!-- end header -->

	<div id="nav">
		<ul>
			<li>
				<%= link_to 'Home', root_path %>
			</li>

			<% if logged_in? %>
				<li>
					<%= link_to "Your Q's", your_questions_path %>
				</li>

			 	<li>
					<%= link_to "Logout #{current_user.username}" , logout_path, method: 'delete' %>
					
				</li>
			 <% else %>
				<li>
					<%= link_to 'Register', register_path %>
				</li>
				<li>
					<%= link_to 'Login', login_path %>
				</li>
			 <% end %> 
			

			
		</ul>
	</div><!-- end nav -->

	<div id="content">
		<% flash.each do |key, value| %>
			<p id="message"><%= value %></p>
		<% end %>
		<%= yield %>
	</div><!-- end content -->

	<div id="footer">
		&copy; Stackoverflow Clone Q&A <%= Date.today.year %> Anmol Agrawal
	</div><!-- end footer -->
</div><!-- end container -->

</body>
</html>

app/views/questions/_question.html.erb
<li>
	<%= link_to truncate(question.body, length: 35), question %> by <%= question.user.username.capitalize %>

	<% if on_your_questions_page? %>
		<%= display_solved(question) %> - <%= link_to 'Edit', edit_question_path(question) %>
	<% end %>

	- (<%= pluralize(question.answers.count, 'answer') %>)
</li>

app/views/questions/_question_form.html.erb
<%= form_for @question do |f| -%>
  <%= render 'common/form_errors', object: @question %>

  <p>
  	<%= f.label :body, "Question" %> <br/>
  	<%= f.text_field :body %>

  	<%= f.submit "Ask a Question" %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<%= provide(:title, 'Edit Your Question') %>

<h1>Edit Your Question</h1>

<%= form_for @question do |f| -%>
  <%= render 'common/form_errors', object: @question %>

  <p>
  	<%= f.label :body, "Body" %> <br/>
  	<%= f.text_field :body %>
  </p>

  <p>
  	<%= f.label :solved, "Solved" %>
  	<%= f.check_box :solved %>
  </p>

  <p>
  	<%= f.submit "Update"%>
  </p>
<% end %>

app/views/questions/index.html.erb
<%= provide(:title, 'Make It Snappy Q&A') %>

<div id="ask">
	<h1>Ask a Question</h1>

	<% if logged_in? %>
		<%= render 'question_form' %>
	<% else %>
		<p>Please login to ask or answer questions.</p>
	<% end %>
</div>

<div id="question">
	<h2>Unsolved Questions</h2>
	<% if @questions.any? %>
		<ul>
			<%= render @questions %>
		</ul>
		<%= will_paginate %>
	<% else %>
		<p>No questions have been asked.</p>
	<% end %>
</div>

app/views/questions/search.html.erb
<%= provide(:title, 'Search Results') %>

<h1>Search Results</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>Nothing found, please try a different search.</p>
<% end %>

app/views/questions/show.html.erb
<%= provide(:title, 'View Question') %>

<h1>
	<%= @question.user.username.capitalize %> asks:
</h1>

<p>
	<%= @question.body %>
</p>

<div id="answers">
	<h2>Answers</h2>
	<% if @question.answers.any? %>
		<ul>
			<%= render @question.answers %>
		</ul>
	<% else %>
		<p>This question has not been answered yet.</p>
	<% end %>
</div>

<div id="post-answer">
	<h2>Answer this question</h2>

	<% if logged_in? %>
		<%= render 'answers/answer_form' %>
	<% else %>
		<p>Please login to post an answer for this question.</p>
	<% end %>
</div>

app/views/questions/your_questions.html.erb
<%= provide(:title, 'Your Questions') %>

<h1>Your Questions</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>You've not asked any questions yet.</p>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Make It Sanappy Q&A - Register') %>

<h1>Register</h1>

<%= form_for @user do |f| %>
  <%= render 'common/form_errors', object: @user %>

  <p>
  	<%= f.label :username, "Username" %> <br/>
  	<%= f.text_field :username %>
  </p>

  <p>
  	<%= f.label :password, "Password" %> <br/>
  	<%= f.password_field :password %>
  </p>

  <p>
  	<%= f.label :password_confirmation, "Confirm Password" %> <br/>
  	<%= f.password_field :password_confirmation %>
  </p>

  <p><%= f.submit "Register"%></p>

<% end %>